orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path("", views.index, name="index"),
    path("feedback/", views.feedback, name="feedback"),
    path("add_review/<uuid:token>/", views.add_review, name="add_review"),
    path("create_request/", views.create_request, name="create_request"),
    path("status_request/", views.request_status, name="request_status"),
    path("privacy/", views.privacy, name="privacy"),
]

washer_repair/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import TemplateView

from orders.sitemaps import StaticSitemap

sitemaps = {
    "static": StaticSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls", namespace="orders")),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "orders.views.page_not_found"
handler500 = "orders.views.server_error"

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="description"
	      content="Ремонт бытовой техники в Орле с гарантией качества и доступными ценами. Бесплатная диагностика и профессиональное обслуживание">
	<meta name="keywords"
	      content="ремонт, стиральная машина, посудомоечная машины, духовой шкаф, варочная панель, Орёл, диагностика, замена подшипников, скидка пенсионерам">
	<meta property="og:title" content="Ремонт бытовой техники в Орле | orel-tech.ru">
	<meta property="og:description"
	      content="Ремонт бытовой техники в Орле с гарантией качества и доступными ценами. Бесплатная диагностика и профессиональное обслуживание">
	<meta property="og:image" content="https://orel-tech.ru/static/washer_repair/images/logo.png">
	<meta property="og:url" content="https://orel-tech.ru">
	<meta property="og:type" content="website">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'washer_repair/images/favicon/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="48x48" href="{% static 'washer_repair/images/favicon/favicon-48x48.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'washer_repair/images/favicon/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'washer_repair/images/favicon/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'washer_repair/images/favicon/site.webmanifest' %}">
	<link rel="mask-icon" href="{% static 'washer_repair/images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'washer_repair/images/favicon/favicon.ico' %}">
	<meta name="apple-mobile-web-app-title" content="orel-tech.ru">
	<meta name="application-name" content="orel-tech.ru">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-config" content="{% static 'washer_repair/images/favicon/browserconfig.xml' %}">
	<meta name="theme-color" content="#ffffff">
	<meta name="yandex-verification" content="88993ae0b775e169"/>
	<link rel="canonical" href="https://orel-tech.ru">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="{% static "washer_repair/css/style.css" %}" type="text/css">
	{% block title %}<title>Ремонт бытовой техники в Орле | Главная</title>{% endblock title %}
</head>
<body>
<div class="wrapper">
	{% block menu %}
		<header class="header">
			<a href="{% url 'orders:index' %}" class="header__logo-link">
				<span class="visually-hidden">Логотип orel-tech</span>
				<img src="{% static "washer_repair/images/logo.png" %}" width="48" height="48"
				     alt="Ремонт стиральных машин в Орле"
				     class="header__logo-pic" loading="lazy">
			</a>
			<div class="wrapper__header">
				<nav class="header__menu">
					<ul class="header__menu-list">
						<li class="header__menu-item">
							<a href="{% url 'orders:index' %}#services" class="header__menu-link">Цены</a>
						</li>
						<li class="header__menu-item">
							<a href="{% url 'orders:index' %}#about" class="header__menu-link">О нас</a>
						</li>
						<li class="header__menu-item">
							<a href="{% url 'orders:index' %}#contact" class="header__menu-link">Контакты</a>
						</li>
						<li class="header__menu-item">
							<a href="{% url "orders:feedback" %}" class="header__menu-link">Отзывы</a>
						</li>
						<li class="header__menu-item">

							<button type="button" class="header__menu-link" hx-get="{% url 'orders:request_status' %}"
							        hx-target="#dialog">
								<span class="visually-hidden">Кнопка для просмотра статуса заявки</span>
								Моя заявка
							</button>
						</li>

					</ul>
				</nav>
				<button type="button" class="header__menu-link-last" hx-get="{% url 'orders:create_request' %}"
				        hx-target="#dialog">
					<span class="visually-hidden">Кнопка оставить заявку</span>
					Оставить заявку
				</button>
			</div>
			<div class="burger">
				<span class="visually-hidden">Открыть меню</span>
				<span></span>
			</div>

			<div class="toast-container position-fixed top-0 start-50 translate-middle-x p-3">
				<div id="toast" class="toast align-items-center text-white fs-5 bg-success border-0" role="alert"
				     aria-live="assertive"
				     aria-atomic="true">
					<div class="d-flex">
						<div id="toast-body" class="toast-body"></div>
						<button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
						        aria-label="Close"></button>
					</div>
				</div>
			</div>
		</header>
	{% endblock menu %}

	{% block header %}
	{% endblock header %}

	{% block content %}
	{% endblock content %}

	{% block footer %}
		<footer class="footer">
			<div class="footer__content">
				<div class="footer-text">
					<p>
						Обработка персональных данных осуществляется в соответствии с ФЗ от 27.07.2006 N 152-ФЗ "О
						персональных данных"
					</p>
					<p>
						ИНН: 572401373001
					</p>
					<p>
						Мы ценим доверие и время наших клиентов, обратившись к нам, вы можете быть уверены в качестве
						предоставляемых услуг
					</p>
				</div>
				<a class="footer-privacy" href="{% url 'orders:privacy' %}">Политика конфиденциальности</a>
			</div>
		</footer>
	{% endblock footer %}
</div>

<div id="modal" class="modal fade">
	<div id="dialog" class="modal-dialog modal-dialog-centered justify-content-center"
	     hx-target="this"></div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
<script src="{% static 'washer_repair/js/scripts.js' %}"></script>
</body>
</html>